### PR TITLE
add BOCF model

### PR DESCRIPTION
**Pull request by Datseris**
Hi @JonasInsensee

So today I spent some 4 hours trying to port the BOCF solver into Julia.

I think I've made it work, and it is okay-ish fast: 1000 time with dt=0.05 takes a couple of seconds on my laptop.

But I am not sure if it is correct. You can use the file `bocf_test.jl` to have a look. For some reason I feel like the dynamics are "really slow". I don't see chaos evolving even after 1000 time units.

There are also some issues regarding python to julia indexing, which makes columns rows and vice versa. But I assumed that because of rotational symmetry of BOCF it shouldn't matter.

You can also check the `# TODO:` comments

### CODE REVIEW

**Comment by JonasIsensee** [comment]
Hi,
thanks for your work.
I've tested your code and it seems to work.
The python code uses `dt=0.1` but I have not experimented with that.
For the dynamics to evolve properly you need larger domains and longer timescales (sadly).
If I remember correctly, one unit of time is meant to resemble one millisecond in a "real" heart.

Integrating until `T=1000` with `N=500` takes about 5 minutes and gives 
spiral_demo

**Comment by Datseris** [comment]
Ah thank god. Okay then tomorrow I wrap it up and I merge it.

**Comment by JonasIsensee** [comment]
> There are also some issues regarding python to julia indexing, which makes columns rows and vice versa. But I assumed that because of rotational symmetry of BOCF it shouldn't matter.

I would be ok with that but we need to clearly state it somewhere. Otherwise someone will someday wonder why the _same_ initial conditions give different results depending on implementation.

**Comment by JonasIsensee** [comment]
For readability one could consider introducing greek symbols instead of the written-out ones.
This should be a simple find-replace step.

**Comment by JonasIsensee** [comment]
At this point the code seems already some 20% faster than the python version
but I think there should be a few more improvements in reach, even though a significant portion of the time seems to be spent on computing the `tanh` function.
You listed some things in the code already. Allowing for `Float32` should also help with that, I think.

One thing to try would be the new threading as most of the heavy computations within a timestep seem to be largely independent, no? ( This would likely only involve putting something like an `@spawn` in front of some of the lines, I think)

I noticed you using a lot of float literals `2.0`. Is that necessary? I always thought that was not needed.

**Comment by Datseris** [comment]
Yeah most of the `TODO` are for performance. But how big portion is spent on `tanh`? because if its like 90%, then it wouldn't be worth the effort to try and improve performance. (except parallelizing)

> One thing to try would be the new threading as most of the heavy computations within a timestep seem to be largely independent, no?

Yes, but after 1.3 comes out, because they plan some parallelization improvements there, and also some new syntax.

> I noticed you using a lot of float literals 2.0. Is that necessary? I always thought that was not needed.

I am convinced that I have read somewhere that this is a tiny bit better for performance, because `2 * x` first converts `2` to `2.0` if `x` if a float. But it was so long ago, maybe this is not even valid anymore.

**Comment by JonasIsensee** [comment]
I'm not sure on a percentage but I would say that reducing allocations could bring things down a bit.
Only worth it though if it doesn't make things a lot more ugly.

Well 1.3 just came out this evening 😎

**Comment by Datseris** [comment]
@JonasIsensee I am searching the GitHub page of the original BOCF solver wegot the code from, but I can't find it. Can you please share the link here?

**Comment by Datseris** [comment]
also: `Base.FastMath.tanh_fast`

**Pull request merged**
